ActiveAdmin.register Invoice do


  member_action :print_invoice do
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf {
        if Rails.env == 'production'
          require 'wkhtmltopdf-heroku'
          render :pdf => "print_factura", :disable_smart_shrinking => false,
                 :template => 'admin/invoices/print_invoice.html.erb', :layout => false,
                 :header => {:font_size => '8', :right => '[page] of [toPage]'},
                 :footer => {:font_size => '8', :right => 'Generated by constructionsupport.co.uk'}
        else
          render :pdf => "print_invoice", :disable_smart_shrinking => false,
                 :template => 'admin/invoices/print_invoice.html.erb', :layout => false,
                 :wkhtmltopdf => 'C:\Program Files (x86)\wkhtmltopdf\wkhtmltopdf.exe',
                 :header => {:font_size => '8', :right => '[page] of [toPage]'},
                 :footer => {:font_size => '8', :right => 'Generated by constructionsupport.co.uk'}
        end
      }
    end
  end
  action_item :only => :show do
    link_to "Print invoice", print_invoice_admin_invoice_path(:format => :pdf)
  end
  form do |f|
    f.inputs "Customer" do
      f.input :customer
    end

    f.has_many :invoice_items do |g|
      g.input :_destroy, :as => :boolean, :label => "Remove this Product" unless g.object.nil? or g.object.id.nil?
      g.input :product_name
      g.input :value
      g.input :quantity
      g.input :discount
      g.input :cis, :as => :boolean, :label => "CIS"
      g.input :vat, :as => :boolean, :label => "VAT"
    end

    f.actions
  end
  show do
    attributes_table do
      row :customer
      row :created_at


    end
    panel "Products" do
      table_for invoice.invoice_items do
        column :id, :width => 100
        column :product_name
        column :value
        column :quantity
        column :discount
        column :cis do |obj|
          obj.cis? ? 'Yes' : 'No'
        end
        column :vat do |obj|
          obj.vat? ? 'Yes' : 'No'
        end
        column :created_at

      end
    end

  end
end