ActiveAdmin.register Invoice do


  member_action :print_invoice do
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf {
        if Rails.env == 'production'
          require 'wkhtmltopdf-heroku'
          render :pdf => "print_invoice", :disable_smart_shrinking => false,
                 :template => 'admin/invoices/print_invoice.html.erb', :layout => false,
                 :header => {:font_size => '8', :right => '[page] of [toPage]'},
                 :footer => {:font_size => '8', :right => 'Generated by constructionsupport.co.uk'}
        else
          render :pdf => "print_invoice", :disable_smart_shrinking => false,
                 :template => 'admin/invoices/print_invoice.html.erb', :layout => false,
                 :wkhtmltopdf => 'C:\Program Files (x86)\wkhtmltopdf\wkhtmltopdf.exe',
                 :header => {:font_size => '8', :right => '[page] of [toPage]'},
                 :footer => {:font_size => '8', :right => 'Generated by constructionsupport.co.uk'}
        end
      }
    end
  end
  member_action :email_invoice,

:only => :show do
    @invoice = Invoice.find(params[:id])
    require 'wkhtmltopdf-heroku'
    pdf = render_to_string :pdf => "print_invoice", :disable_smart_shrinking => false,
                 :template => 'admin/invoices/print_invoice.html.erb', :layout => false,

                 :header => {:font_size => '8', :right => '[page] of [toPage]'},
                 :footer => {:font_size => '8', :right => 'Generated by constructionsupport.co.uk'}

   CustomerMailer.email_invoice(@invoice,pdf).deliver
    redirect_to admin_invoice_path(:notice => "Email sent")
  end


  action_item :only => :show do
    link_to "Print invoice", print_invoice_admin_invoice_path(:format => :pdf)
  end
  action_item :only => :show do
    link_to "Send invoice by e-mail", email_invoice_admin_invoice_path
  end


  form do |f|

    f.inputs "Customer" do
      f.input :customer
      if f.object.new_record?
      f.input :invoice_number, :input_html => {:size => 2, :readonly => true, :value => "#{Invoice.order('created_at desc').first.invoice_number.to_i + 1}"},
              :label => 'Invoice number <a href="#" onclick="$(\'#invoice_invoice_number\').attr(\'readonly\',false);">change</a>'.html_safe
      else
        f.input :invoice_number, :input_html => {:size => 2, :readonly => true},
                :label => 'Invoice number <a href="#" onclick="$(\'#invoice_invoice_number\').attr(\'readonly\',false);">change</a>'.html_safe
      end
      f.input :due_date, :as => :radio, :collection => [["15 days", 15], ["30 days", 30], ["45 days",45],["60 days",60]]
      end




    f.has_many :invoice_items do |g|
      g.input :_destroy, :as => :boolean, :label => "Remove this Product" unless g.object.nil? or g.object.id.nil?
      g.input :product_name, :required => true
      g.input :value, :required => true
      g.input :quantity, :required => true
      g.input :discount, :input_html => {:value => "0.00"}
      g.input :cis, :as => :boolean, :label => "CIS"
      g.input :vat, :as => :boolean, :label => "VAT"
    end

    f.actions
  end
  show do
    attributes_table do
      row :invoice_number
      row :customer
      row :due_date do |obj|
         d = obj.due_date.to_i
        obj.created_at + d.day
      end
      row :created_at




    end
    panel "Products" do
      table_for invoice.invoice_items do
        column :id, :width => 100
        column :product_name

        column :quantity
        column :discount
        column :cis do |obj|
          obj.cis? ? 'Yes' : 'No'
        end
        column :vat do |obj|
          obj.vat? ? 'Yes' : 'No'
        end
        column "Net value", :value
        column "VAT Value", :value do |obj|
          obj.vat? ? obj.value/5 : "0.00"
        end
        column "Gross", :value do |obj|
          obj.vat? ?  obj.value*6/5 : obj.value
        end

        column :created_at

      end
    end

  end
end